<a href="https://colab.research.google.com/github/yogi2034/Deep-Learning/blob/main/000pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

webpage : https://www.learnpytorch.io/

YT : https://www.youtube.com/watch?v=Z_ikDlimN6A

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
print("back to roots")

back to roots


In [3]:
# !pip install torch

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


**Tensors**

In [5]:
scalar =torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector=torch.tensor([4,4,55])

In [9]:
vector

tensor([ 4,  4, 55])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([3])

In [12]:
mat =torch.tensor([[1,2,3],[4,5,6]])

In [13]:
mat
mat.ndim

2

In [14]:
mat.shape

torch.Size([2, 3])

In [15]:
mat.size

<function Tensor.size>

In [16]:
tensor=torch.tensor([[[1,2,3],
                        [4,5,6],
                           [5,6,7]]])

In [17]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 6, 7]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

In [20]:
tensor[0][2][2]

tensor(7)

# **Random**

In [21]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4124, 0.2842, 0.0615, 0.2387],
        [0.8502, 0.1089, 0.4865, 0.8696],
        [0.9088, 0.6404, 0.1555, 0.9841]])

In [22]:
image_size_tensor= torch.rand((224,224,3))
image_size_tensor.shape,image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
  zeros=torch.zeros(3,4)
  zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
random_tensor

tensor([[0.4124, 0.2842, 0.0615, 0.2387],
        [0.8502, 0.1089, 0.4865, 0.8696],
        [0.9088, 0.6404, 0.1555, 0.9841]])

In [26]:
random_tensor.dtype

torch.float32

### Range

In [27]:
 one_to_ten=torch.range(1,11,2)
 one_to_ten

<ipython-input-27-fd32a49b9e12>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten=torch.range(1,11,2)


tensor([ 1.,  3.,  5.,  7.,  9., 11.])

In [28]:
one_to_tens =torch.arange(1,-12,-1)
one_to_tens

tensor([  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11])

In [29]:
ten_zeros=torch.zeros_like(one_to_tens)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Main error we may run into

1.   tensors not right datatype -tensor.dtype
2.   " shape -tensor.shape
3.    " on the right device -tensor.device




In [30]:
float_32_tensor = torch.tensor([3,4,5],dtype=None)
float_32_tensor

tensor([3, 4, 5])

In [31]:
float_16_tensor=float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [32]:
int_32_tensor=torch.tensor([3,4,5],dtype=torch.int32)

In [33]:
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [34]:
float_16_tensor*int_32_tensor

tensor([ 9., 16., 25.], dtype=torch.float16)

In [35]:
some_tensor =torch.rand(3,4)
some_tensor


tensor([[0.4241, 0.1763, 0.6249, 0.6704],
        [0.8799, 0.1827, 0.4286, 0.6463],
        [0.5668, 0.4326, 0.9047, 0.5420]])

In [36]:
some_tensor.size() ,some_tensor.shape,some_tensor.device,some_tensor.size

(torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'),
 <function Tensor.size>)

# **TensorOps**

In [37]:
tensor=torch.tensor([1,2,3])
tensor+=10


In [38]:
tensor*=10
tensor

tensor([110, 120, 130])

In [39]:
tensor-=10

In [40]:
tensor

tensor([100, 110, 120])

In [41]:
tensor=torch.tensor([3,4,2])

In [42]:
torch.mul(tensor,5)

tensor([15, 20, 10])

In [43]:
torch.add(tensor,10)

tensor([13, 14, 12])

In [44]:
x= (tensor*tensor)

In [45]:
x

tensor([ 9, 16,  4])

In [46]:
torch.matmul(tensor,tensor)

tensor(29)

In [47]:
torch.tensor([[3,4,5],[43,5,5]]).T

tensor([[ 3, 43],
        [ 4,  5],
        [ 5,  5]])

In [48]:
tensor_A=torch.rand([3,2])
tensor_B=torch.rand([2,3])
tensor_C=torch.matmul(tensor_A,tensor_B)
tensor_C

tensor([[1.0045, 0.3525, 0.8983],
        [0.7945, 0.2309, 0.4094],
        [0.9080, 0.2746, 0.5351]])

#Aggregation Functions (Min ,Max ..)

In [49]:
x=torch.arange(0,-100,-5)


torch.min(x)
x.min()

tensor(-95)

In [50]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(-47.5000), tensor(-47.5000))

In [51]:
  x.sum()

tensor(-950)

In [52]:
x.argmin()

tensor(19)

 Reshape ,Squeeze,stack,torch.unsqueeze

In [87]:
x=torch.arange(1,10)
x.shape

torch.Size([9])

In [105]:

x_reshaped =x.reshape([3,3])
x_reshaped

tensor([[1, 5, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
x_reshaped.shape

torch.Size([3, 3])

In [90]:
z=x.view(1,9)

In [91]:
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [92]:
z[0,1]=5
z,x

(tensor([[1, 5, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 5, 3, 4, 5, 6, 7, 8, 9]))

In [101]:
x_stacked =torch.stack([x,x,x],dim=-2)
x_stacked

tensor([[1, 5, 3, 4, 5, 6, 7, 8, 9],
        [1, 5, 3, 4, 5, 6, 7, 8, 9],
        [1, 5, 3, 4, 5, 6, 7, 8, 9]])

In [102]:
x_reshaped.squeeze()

tensor([[1, 5, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
x_reshaped.squeeze().squeeze()

tensor([[1, 5, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [110]:
x_usq =x_reshaped.unsqueeze(2)
x_usq

tensor([[[1],
         [5],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [127]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x,0)
y
y.size()


torch.Size([2, 1, 2, 1, 2])

In [129]:
# y = torch.squeeze(x, 0)
# y.size()
# y = torch.squeeze(x, 1)
# y.size()
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [133]:
y =torch.rand(size =(224,224,3))


In [137]:
x_perm=y.permute(2,1,0)
# x_perm

In [139]:
y[0,0,0]=3004
y[0,0,0],x_perm[0,0,0]

(tensor(3004.), tensor(3004.))

#Indexing

In [140]:
 x=torch.arange(1,10).reshape(1,3,3)
 x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [142]:
x[0][0][0]

tensor(1)

In [152]:
x[:,:,2]

tensor([[3, 6, 9]])

#Pytorch tensors and numpy
from numpy to pytorch
-> torch.from_numpy(ndarray)

from pytorch to numpy
-> torch.Tensor.numpy()

In [162]:
array =np.arange(1,8)
tensor =torch.from_numpy(array)
array,tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [163]:
array.dtype

dtype('int64')

In [167]:
 array+=1
 tensor, array

(tensor([ 5,  6,  7,  8,  9, 10, 11]), array([ 5,  6,  7,  8,  9, 10, 11]))

In [168]:
 tensor=torch.ones(7)
 numpy_tensor=tensor.numpy()
 tensor,numpy_tensor
 tensor+=1
 tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

#Reproducibility

In [173]:
seed=42
torch.man  ual_seed(seed)
random_tensor_C =torch.rand(3,4)
torch.manual_seed(seed)
random_tensor_D =torch.rand(3,4)

print(random_tensor_C==random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
