<a href="https://colab.research.google.com/github/yogi2034/Deep-Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch
tensor =torch.rand(7,7)
tensor
# Create random tensor


tensor([[0.3552, 0.0603, 0.2967, 0.9567, 0.2742, 0.2583, 0.3185],
        [0.0150, 0.1044, 0.0656, 0.2308, 0.8243, 0.7485, 0.9719],
        [0.8342, 0.9669, 0.7576, 0.0850, 0.2762, 0.8583, 0.1355],
        [0.0083, 0.0539, 0.2200, 0.6182, 0.5146, 0.4043, 0.7763],
        [0.2744, 0.6753, 0.0312, 0.2842, 0.3547, 0.9644, 0.1605],
        [0.1831, 0.8098, 0.3031, 0.1145, 0.9673, 0.7102, 0.6229],
        [0.0828, 0.1694, 0.9971, 0.1712, 0.3248, 0.0917, 0.0572]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_x=tensor@torch.rand(1,7).T
tensor_x
# Perform matrix multiplication


tensor([[1.0310],
        [1.2584],
        [2.1600],
        [1.0542],
        [1.2021],
        [1.6481],
        [1.1039]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [12]:
# Set manual seed
seed =torch.cuda.manual_seed((1729))




### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)







device:cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [36]:
# Set random seed

torch.manual_seed(1234)
# Check for access to GPU
device ="cuda" if torch.cuda.is_available() else "cpu"
print(f"device:{device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2,3).to(device);

tensor_B = torch.rand(2,3).to(device);
tensor_A,tensor_B


device:cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [38]:
# Perform matmul on tensor_A and tensor_B

c=tensor_A@tensor_B.reshape(3,2)
c,c.shape
tensor_C=torch.matmul(tensor_A,tensor_B.T)
tensor_C,tensor_C.shape



(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [40]:
# Find max
tensor_c.min(),tensor.max()
# Find min


(tensor(0.0162), tensor(0.9971))

### 9. Find the maximum and minimum index values of the output of 7.

In [43]:
# Find arg max
x=torch.argmin(tensor_C)

# Find arg min
y=torch.argmax(tensor_C)
x,y



(tensor(0), tensor(3))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
torch.manual_seed(7)

# Create random tensor
ten_A=torch.rand(1,1,1,10)

# Remove single dimensions
ten_As=ten_A.squeeze()

# Print out tensors and their shapes
ten_A,ten_As.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([10]))